In [1]:
#python list to create vectors 
[4,2,10.2]

[4, 2, 10.2]

In [2]:
#python list is very inefficient
# each element actually holds a lot of info , like data type 
#python is built under c
#pyhton is a wrapper so 4 here is actually a manifestation of a lot of 

#numpy
#numpy forces us to use only fixed type list
#numpy -each element ony holds minimal info

import numpy as np
house=np.array([4,2,10.2])
print(house)
print(house.shape) #number of rows and coloumns

#once its 3d 4d there are no such things as rows and cols

#house.shape(m_feature, n_sample ) ==> (3,)

[ 4.   2.  10.2]
(3,)


In [5]:
x= np.array([
    [4,2],
    [2,1],
    [10.2,4]
])
x.shape #(m_feature, n_samples)

(3, 2)

#scalar multiplication
$$\alpha$$
$$\gamma$$
$$\beta$$

$$\frac{1}{2}$$
$$\Sigma_{i=1}^{n}\frac{y_i -}$$

In [8]:
alpha =3 
print(alpha * x)

print (x * alpha)



[[12.   6. ]
 [ 6.   3. ]
 [30.6 12. ]]
[[12.   6. ]
 [ 6.   3. ]
 [30.6 12. ]]


In [10]:
print ("X shape: ", x.shape)
print ("b shape: ", b.shape)


X shape:  (3, 2)


NameError: name 'b' is not defined

In [11]:
#np.dot
print(np.dot(x.T,b))

#.dot
#all numpy type have .dot
print(type(x))
print(x.T @b)
#matrix multiplication
np.matmul(x.t,b) #only allow matrix multiplication 
#dot allows scalar, vector , matrix

NameError: name 'b' is not defined

In [13]:
print(x.T.shape)
print((x.T@b).shape)

b.reshape = b.reshape(3,1)

print((x.T@b_reshape).shape)

#whether b should be shape(m_features,) or (m_features,1)
#depend on your y
#if 

(2, 3)


NameError: name 'b' is not defined

In [16]:
#not commutative law
#QR != RQ
#Q (2,3)
#R (3,2)
#QR(2,2)
# RQ (3,3)

Q= np.random.rand(2,3)
R  = np.random.rand(3,2)
print((Q @ R).shape)
print((R @ Q).shape)

#associative
#order of operation does not matter
#Q(RS) == (QR)S
 
S = np.random.rand(2,5)
print(Q @(R @S))
print((Q @R) @S)

(2, 2)
(3, 3)
[[1.04696211 0.96439573 0.31384481 0.93247325 0.69344624]
 [0.95694052 0.88685069 0.27703935 0.85694773 0.64138945]]
[[1.04696211 0.96439573 0.31384481 0.93247325 0.69344624]
 [0.95694052 0.88685069 0.27703935 0.85694773 0.64138945]]


In [21]:
print((Q @(R @ S)).shape)
print(((Q @ R) @ S).shape)

(2, 5)
(2, 5)


In [ ]:
#distributive
#(Q +R)S = QS + RS

Q

In [ ]:
#addition
#A+B #A.shape = B.shape

In [23]:
#Vectors as arrows 
#arrow has two properties
#1. direction 
#2. magnitude/length

u= np.array([2,5])
v=np.array([3,1])

import matplotlib.pyplot as plt
x,y = zip(u,v)
plt.scatter(x,y)
plt.axis([0,9,0,6])
plt.grid()

ModuleNotFoundError: No module named 'matplotlib'

In [24]:
###unit vectors
plot_arrow(u,color="b")

plt.grid()
plt.axis([0,6,0,9])

NameError: name 'plot_arrow' is not defined

In [25]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [27]:
print (x)

[[ 4.   2. ]
 [ 2.   1. ]
 [10.2  4. ]]


In [29]:
#x @ ? =x
#? @ x = x

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
Im = np.eye(3)
In = np.eye(2)

print(x @ In)

[[ 4.   2. ]
 [ 2.   1. ]
 [10.2  4. ]]


In [35]:
print(Im @ x )

[[ 4.   2. ]
 [ 2.   1. ]
 [10.2  4. ]]


In [36]:
### matrix operations
#addition
from matplotlib.patches import Polygon

P= np.array([
    [3.0,4.0, 1.0,4.6],
    [0.2,3.5,2.0,0.5]
])

H = np.array([
    [0.5,-0.2,0.2,-0.1],
    [0.4,0.4,1.5,0.6]
])

P_moved = P + H

plt.gca().add_artist(Polygon(P.T, alpha=0.2))
plt.gca().add_artist(Polygon(P_move, alpha=0.2, color="r")) #addition is shifting of the matrix
plt.axis([0, 5, 0, 4])
plt.grid()

ModuleNotFoundError: No module named 'matplotlib'

In [37]:
#Scalar multiplication
def plot_transform(P_before, P_after, axis=[0,5,0,4]):
    plt.gca().add_artist(Polygon(P_before.T, alpha=0.2))
    plt.gca().add_artist(Polygon(P_after.T, alpha=0.3, color="r"))
    plt.axis(axis)

plot_transform(P,P_scaled)

SyntaxError: invalid syntax (<ipython-input-37-8f9d1e0000cd>, line 2)

In [42]:
#transformations
# F @ P
# P is out given vector 
# F si the transformation
# F can be any tranformation that we want to achieve

u = np.array([1,0])
print(u.dot(p))

NameError: name 'p' is not defined

In [43]:
def plot_projection(u,p):
    u_p = u.dot(p)
    plt.gca().add_artist(Polygon(P.T, alpha=0.2))
    for vector, proj in zip(p.T, u_p.T):
        proj_point = proj * u
        print(proj_point)
        plt.plot(proj_point[0][0], proj_point[0][1], "ro")
        plt.plot(vector[0], proj_point[0][0])
    plt.axis[0,5,0,4]     

In [50]:
#rotation
#rotation around z-axis
#transform matrix = [cos -sin]
                  # [sin cos]
def rotateZ(angle):
    c = np.cos(np.radians(angle))
    s = np.sin(np.radians(angle))
    return np.array([[c, -s], [s, c]])

u_rotated = rotateZ(30).dot(u)

In [ ]:
#Singular decompossitions